services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - laravel-storage-production:/var/www/storage:ro
      - laravel-public-assets:/var/www/public/build:ro
    networks:
      - laravel-production
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - laravel-public-assets:/var/www/public/build
      - laravel-storage-production:/var/www/storage
    env_file:
      - .env
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MARIADB_DATABASE=${DB_DATABASE:-app}
      - MARIADB_USER=${DB_USERNAME:-laravel}
      - MARIADB_PASSWORD=${DB_PASSWORD:-secret}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-secret_root}
    volumes:
      - mariadb-data-production:/var/lib/mysql
    networks:
      - laravel-production
    # Health check for MariaDB
    # -----------------------------------------------------------
    # Using mariadb-admin to ensure the database is ready to accept connections.
    # -----------------------------------------------------------
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "--password=${MARIADB_ROOT_PASSWORD:-secret_root}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  laravel-production:

volumes:
  mariadb-data-production:
  laravel-storage-production:
  laravel-public-assets: